repository_type: pipeline
lint:
  files_exist:
    - assets/nf-core-genomenote_logo_light.png
    - docs/images/nf-core-genomenote_logo_light.png
    - docs/images/nf-core-genomenote_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - LICENSE
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - lib/NfcoreTemplate.groovy
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
